server:
  port: 8080
  shutdown: graceful

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: false

    properties:
      hibernate:
        format_sql: false

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    root: INFO
    com.healthcare: INFO

  file:
    name: logs/healthcare-prod.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      show-details: when-authorized